# Generated by Django 5.2 on 2025-04-12 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catblog', '0005_category_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
