# Generated by Django 5.2 on 2025-04-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catblog', '0003_alter_post_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='active_post',
            field=models.BooleanField(default=True),
        ),
    ]
