# Generated by Django 5.2 on 2025-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catblog', '0008_alter_post_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='catblog.tag'),
        ),
    ]
