# Generated by Django 5.2 on 2025-04-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
