# Generated by Django 5.2 on 2025-04-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catblog', '0009_tag_alter_post_id_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='catblog.tag'),
        ),
    ]
