# Generated by Django 5.2.1 on 2025-05-30 23:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('content', models.TextField(max_length=1000, verbose_name='Contenido')),
                ('publish_date', models.DateField(default=django.utils.timezone.now, help_text='aa-mm-dd', verbose_name='Fecha de Publicación')),
                ('active_post', models.BooleanField(default=True, verbose_name='Activo')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catblog.category', verbose_name='Categoría')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('tags', models.ManyToManyField(to='catblog.tag', verbose_name='Etiquetas')),
            ],
        ),
    ]
